### ISSUE TITLE
TODO Next Round

### ISSUE THREAD

**Issue by pdwaggoner** [pdwaggoner/hdImpute#3]
Add helpers...
- [x] to check NAs (row, col, and full df)

Add testing...
- [x] to throw error if a col (or more than one) contains all NA; making up data at that point. Suggest use of pre-processing function (below) to drop these columns based on some percentage set by the user

Add pre-processing options, e.g.: 
- [ ] cleaning to drop columns with more than X% missing values (optional argument)
- [ ] cleaning to separate demographic features from all others (optional argument)
- [ ] cleaning to define `dropped` subset of data, minus above two subsets of columns

Add post-processing options, e.g.:
- [x] join imputed sets (minus demographic features, if selected in pre-processing) with demographic subset (optional argument)

**Comment by pdwaggoner** [comment]
made relevant changes and avoided suggestions that don't make sense. Also, not included on this list of suggestions is the addition of the evaluative `mad()` scores metric. Included in latest release (v0.2.1)
